<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
	  <Nullable>enable</Nullable>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <NoWarn>$(NoWarn);1591</NoWarn>
	  <NugetAuditMode>Direct</NugetAuditMode>
    <UserSecretsId>dotnet-MorenoSeguros.Migration-3f9e67a8-fa0c-4341-957f-edc65ba76c66</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.3.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MorenoSeguros.Infrastructure\MorenoSeguros.Infrastructure.csproj" />
  </ItemGroup>
</Project>
