// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorenoSeguros.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MorenoSeguros.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250331021036_Company_Plan_And_Deductible_Tables")]
    partial class Company_Plan_And_Deductible_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MorenoSeguros.Core.Entities.CompanyAggregate.InsuranceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InsuranceCompany", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.DeductibleOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DeductibleFamily")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeductibleIndividual")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("InsurancePlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("DeductibleOption", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("InsuranceCompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceCompanyId");

                    b.ToTable("InsurancePlan", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.DeductibleOption", b =>
                {
                    b.HasOne("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", "InsurancePlan")
                        .WithMany("DeductibleOptions")
                        .HasForeignKey("InsurancePlanId");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", b =>
                {
                    b.HasOne("MorenoSeguros.Core.Entities.CompanyAggregate.InsuranceCompany", "InsuranceCompany")
                        .WithMany("Plans")
                        .HasForeignKey("InsuranceCompanyId");

                    b.Navigation("InsuranceCompany");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.CompanyAggregate.InsuranceCompany", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", b =>
                {
                    b.Navigation("DeductibleOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
