// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorenoSeguros.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MorenoSeguros.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MorenoSeguros.Core.Entities.ClientAggregate.Clients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmploymentStatus")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FundOrigin")
                        .HasColumnType("text");

                    b.Property<string>("IncomeRange")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.CompanyAggregate.InsuranceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InsuranceCompany", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.DeductibleOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DeductibleFamily")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeductibleIndividual")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("InsurancePlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("DeductibleOption", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("InsuranceCompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceCompanyId");

                    b.ToTable("InsurancePlan", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BankAccount", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.Payments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeductibleOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeductibleOptionId1")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("InsurancePlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousPolicyNumber")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TitularClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("DeductibleOptionId");

                    b.HasIndex("DeductibleOptionId1");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("PreviousPolicyNumber");

                    b.HasIndex("TitularClientId");

                    b.ToTable("Policy", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.PolicyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("Exclusions")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTitular")
                        .HasColumnType("boolean");

                    b.Property<string>("MemberType")
                        .HasColumnType("text");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyMember", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.DeductibleOption", b =>
                {
                    b.HasOne("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", "InsurancePlan")
                        .WithMany("DeductibleOptions")
                        .HasForeignKey("InsurancePlanId");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", b =>
                {
                    b.HasOne("MorenoSeguros.Core.Entities.CompanyAggregate.InsuranceCompany", "InsuranceCompany")
                        .WithMany("Plans")
                        .HasForeignKey("InsuranceCompanyId");

                    b.Navigation("InsuranceCompany");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.Payments", b =>
                {
                    b.HasOne("MorenoSeguros.Core.Entities.PolicyAggregate.Policy", "Policy")
                        .WithMany("Payments")
                        .HasForeignKey("PolicyNumber")
                        .HasPrincipalKey("PolicyNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.Policy", b =>
                {
                    b.HasOne("MorenoSeguros.Core.Entities.UserAggregate.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("MorenoSeguros.Core.Entities.PolicyAggregate.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId");

                    b.HasOne("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.DeductibleOption", "DeductibleOption")
                        .WithMany()
                        .HasForeignKey("DeductibleOptionId");

                    b.HasOne("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.DeductibleOption", null)
                        .WithMany("Policies")
                        .HasForeignKey("DeductibleOptionId1");

                    b.HasOne("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId");

                    b.HasOne("MorenoSeguros.Core.Entities.PolicyAggregate.Policy", null)
                        .WithMany()
                        .HasForeignKey("PreviousPolicyNumber")
                        .HasPrincipalKey("PolicyNumber");

                    b.HasOne("MorenoSeguros.Core.Entities.ClientAggregate.Clients", "TitularClient")
                        .WithMany()
                        .HasForeignKey("TitularClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("BankAccount");

                    b.Navigation("DeductibleOption");

                    b.Navigation("InsurancePlan");

                    b.Navigation("TitularClient");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.PolicyMember", b =>
                {
                    b.HasOne("MorenoSeguros.Core.Entities.ClientAggregate.Clients", "Client")
                        .WithMany("PolicyMemberships")
                        .HasForeignKey("ClientId");

                    b.HasOne("MorenoSeguros.Core.Entities.PolicyAggregate.Policy", "Policy")
                        .WithMany("PolicyMembers")
                        .HasForeignKey("PolicyId");

                    b.Navigation("Client");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.ClientAggregate.Clients", b =>
                {
                    b.Navigation("PolicyMemberships");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.CompanyAggregate.InsuranceCompany", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.DeductibleOption", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.InsuranceCompanyAggregate.InsurancePlan", b =>
                {
                    b.Navigation("DeductibleOptions");
                });

            modelBuilder.Entity("MorenoSeguros.Core.Entities.PolicyAggregate.Policy", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PolicyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
