export const CustomerEventTable = [
    { columnDef: 'documentNumber', header: 'DOCUMENTO', type: 'text' },
    { columnDef: 'firstName', header: 'NOMBRE', type: 'text' },
    { columnDef: 'lastName', header: 'APELLIDO', type: 'text' },
    { columnDef: 'birthDate', header: 'FECHA DE NACIMIENTO', type: 'text' },
    { columnDef: 'phoneNumber', header: 'TELÉFONO', type: 'text' },
    { columnDef: 'email', header: 'EMAIL', type: 'text' },
    { columnDef: 'gender', header: 'GÉNERO', type: 'text' },
    { columnDef: 'city', header: 'CIUDAD', type: 'text' },
    { columnDef: 'archetype', header: 'ARQUETIPO', type: 'text' },
    { columnDef: 'event', header: 'EVENTO', type: 'text' },
    { columnDef: 'onlineRegistrationDate', header: 'FECHA PREREGISTRO', type: 'text' },
    { columnDef: 'onsiteRegistrationDate', header: 'FECHA REGISTRO PRESENCIAL', type: 'text' },
    { columnDef: 'entryDate', header: 'FECHA DE INGRESO', type: 'text' },
    { columnDef: 'standAssignmentDate', header: 'FECHA DE ASIGNACIÓN DE STAND', type: 'text' },
    { columnDef: 'regIngress', header: 'PERSONAL INGRESO', type: 'text' },
    { columnDef: 'concierge', header: 'CONCIERGE', type: 'text' },
    { columnDef: 'hasTraveledAbroad', header: '¿HA VIAJADO AL EXTRANJERO?', type: 'boolean' },
    { columnDef: 'hasSpecificTravelDate', header: '¿TIENE FECHA DE VIAJE?', type: 'boolean' },
    { columnDef: 'hasSpecificDestination', header: '¿TIENE DESTINO ESPECÍFICO?', type: 'boolean' },
    { columnDef: 'ticketOrPackageInterest', header: 'INTERÉS EN BOLETOS O PAQUETES', type: 'text' },
    { columnDef: 'paymentMethod', header: 'MÉTODO DE PAGO', type: 'text' },
    { columnDef: 'stand', header: 'STAND', type: 'text' },
    { columnDef: 'origin', header: 'ORIGEN', type: 'text' },
    { columnDef: 'travelExperience', header: 'EXPERIENCIA DE VIAJE', type: 'text' }
];
