<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
	  <Nullable>enable</Nullable>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <OutputType>Library</OutputType>
	  <NoWarn>$(NoWarn);1591</NoWarn>
	  <NugetAuditMode>Direct</NugetAuditMode>
    <!--<UserSecretsId>dotnet-MorenoSeguros.Core-915fd853-580e-4bec-90e4-f5adec0f4983</UserSecretsId>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" Version="8.2.0" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\ClientAggregate\Specfication\" />
    <Folder Include="Entities\PolicyAggregate\Specification\" />
    <Folder Include="SharedKernel\Extensions\" />
  </ItemGroup>
</Project>
